// Action types constants
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';

export const LOAD_TODOS_ERROR = 'LOAD_TODOS_ERROR';
export const CREATE_UPDATE_TODO_ERROR = 'CREATE_UPDATE_TODO_ERROR';
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR';
